# http://travis-ci.org/#!/RDFLib/rdflib-mysql
language: python
branches:
  only:
    - master
env:
    - DB=mysql
python:
    # - 2.5
    # - 2.6
    - 2.7
    # - 3.2
    # - 3.3
install:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install -r requirements-py2.txt --use-mirrors; fi
    # - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then pip install -r requirements-py3.txt --use-mirrors; fi
    - python setup.py install
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test'; fi"
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then nosetests; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests --where=./build/src; fi
